import type { Metadata } from "next";
import { Alegreya, Alegreya_Sans } from "next/font/google";
import "./globals.css";

const alegreya = Alegreya({
  subsets: ["latin"],
  variable: "--font-alegreya",
});

const alegreyaSans = Alegreya_Sans({
  weight: "500",
  subsets: ["latin"],
  variable: "--font-alegreya-sans",
});


export const metadata: Metadata = {
  title: "Drape",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alegreya.variable} ${alegreyaSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
